services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    networks:
      - app-network
    develop:
      watch:
        - path: ./client/src
          target: app/src
          action: sync
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - app-network
    develop:
      watch:
        - path: ./server/src
          target: server/src
          action: sync
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    env_file: ".env"
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
networks:
  app-network:
    driver: bridge