services:
  server:
    build: .
    ports:
      - '5000:5000'
    container_name: server
    depends_on:
      - db
    develop:
      watch:
        - path: ./src
          target: app/src
          action: sync

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: links
