services:
  server:
    build: .
    ports:
      - '5000:5000'
    container_name: server
    depends_on:
      - db
    develop:
      watch:
        - path: ./src
          target: app/src
          action: sync

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local